### PR TITLE
feat: update gh actions yml

### PR DESCRIPTION
**Pull request by Mo3et**
[The latest Actions](https://github.com/go-kratos/go-kratos.dev/actions/runs/3273414630) running has the [problem](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).  
So update the checkout version and the [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) version. But the **actions-gh-pages** latest release no solve this problem. The reference [issue](https://github.com/peaceiris/actions-gh-pages/issues/677) is open.
I have replaced the old version with [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action).

### CODE REVIEW

**Comment by Mo3et** [comment]
Ref: [New GitHub pages action](https://github.com/marketplace/actions/deploy-to-github-pages)

**Comment by Mo3et** [comment]
[new actions test](https://github.com/Mo3et/go-kratos.dev/actions/runs/3274038606)

**Comment by Mo3et** [comment]
Because the [issue](https://github.com/peaceiris/actions-gh-pages/issues/677) is resolved and [released](https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.9.0).  
So I go back to the [original actions version](https://github.com/marketplace/actions/github-pages-action) and upgrade the version to [v 3.9.0](https://github.com/marketplace/actions/github-pages-action?version=v3.9.0) in the latest commits.

**Comment by Mo3et** [comment]
@Windfarer

**Review by haiyux — APPROVED** [review]

**Pull request merged**
